parameters:
  databricksbundle:
    enableNotebookErrorHandler: True

    notebook:
      serviceResolvers:
        logging.Logger: '@databricksbundle.notebook.function.service.LoggerResolver'
        box.Box: '@databricksbundle.notebook.function.service.NotebookParamsResolver'

services:
  databricksbundle.notebook.function.ArgumentResolver:
    arguments:
      - '%databricksbundle.notebook.serviceResolvers%'

  databricksbundle.notebook.function.ArgumentsResolver:

  databricksbundle.notebook.function.service.LoggerResolver:

  databricksbundle.notebook.function.service.NotebookParamsResolver:

  databricksbundle.notebook.NotebookPathResolver:
