parameters:
  databricksbundle:
    enableNotebookErrorHandler: True

    pipeline:
      serviceResolvers:
        logging.Logger: '@databricksbundle.pipeline.function.service.LoggerResolver'

services:
  databricksbundle.pipeline.function.ArgumentResolver:
    arguments:
      - '%databricksbundle.pipeline.serviceResolvers%'

  databricksbundle.pipeline.function.ArgumentsResolver:

  databricksbundle.pipeline.function.service.LoggerResolver:
